backend:
  backend: github
  name: flquenano/minimalist-portfolio-netlify
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blogPosts"
